### ISSUE TITLE
Take it easy

### ISSUE THREAD

**Issue by bucaran** [fish-shell/oh-my-fish#559]
The original OMF was OK. @bpinto and I worked together for a while and improved it a lot and for a while it was good. Most plugins sucked, but that was alright.

But then I realized this is too complex and we could do simpler and better at the same time. I left and Wahoo was born.

We are back together again, which is great, but I already see this is starting to get out of hand.

**Comment by bpinto** [comment]
I don't agree. Wahoo had a infrastructure  that was better mostly because the code was done 2 years after. But many features were broken (see all bug fixes that happened in the past days) and others were lacking.

What we are doing now is bringing all cool features and plugins (we almost don't have plugins now) existing omf users expect and that wahoo users haven't dream of yet. :)

Both will become delightful.

**Comment by bpinto** [comment]
Things are only coming inside the project with the approval of the community, so raise your voice in case your are against one of the changes and everyone will discuss it.

**Comment by bucaran** [comment]
> But many features were broken (see all bug fixes that happened in the past days) and others were lacking.

Which ones? Wahoo's original source code is still available. I would really like to look into this as I really doubt there were any major features broken.

**Comment by bpinto** [comment]
Here is a list of fixes we did in the past two days:

1. https://github.com/fish-shell/oh-my-fish/pull/516
2. https://github.com/fish-shell/oh-my-fish/commit/4809687b52eeb0201658cdce4055cae8b1d3d1e4, https://github.com/fish-shell/oh-my-fish/commit/4809687b52eeb0201658cdce4055cae8b1d3d1e4, https://github.com/fish-shell/oh-my-fish/commit/718ba2fc10a8e458c47462430077cab08218fac8
3. https://github.com/fish-shell/oh-my-fish/commit/c6e72863bdd3a86553798b3e62189af33e6368c4
4. https://github.com/fish-shell/oh-my-fish/issues/545
5. https://github.com/fish-shell/oh-my-fish/issues/535

Anyway, IMO you should stop acting like you are the code owner and start acting as a community manager, you would be doing much better for the fish community.

**Comment by bucaran** [comment]
#516 is not a bug, that was the default behavior.
#545 I don't think is a good idea to remove custom themes :disappointed: 
#535 What do you mean by updating custom plugins?

Don't internalize any of this stuff, I am not the code owner, but I was hoping to protect the simplicity of the framework. Changes are occurring too fast.

**Comment by bpinto** [comment]
#516 is a bug, there is not (or wasn't) a theme called default so we shouldn't prevent it from being deleted.
#545 we were saying the custom theme was deleted but it was not, I think we should remove but with a confirmation, same for 'omf destroy" that currently has no confirmation before destroying itself.
#535 See the issue, when calling 'omf update' an error message is being raised instead of updating the custom theme.

Anyway, my concern at the moment is that recent comments are not related to OMF but to other personal feelings. Let's try to keep the focus when commenting on PRs and issues and let's talk on gitter.

We have worked together for a long time and I know you are not like this, so something must be affecting you. Let's have a talk and drink a beer!

**Comment by bucaran** [comment]
#516 I don't get it. Originally (Wahoo) there _was_ a `default` theme. We then removed it, now it's back :smile: 
#535 Ah, yes. Updating plugins that were downloaded via a URL was not implemented in Wahoo. You are correct in this point.
#545 I have replied in the relevant issue.

:+1:
